var tableauQuestion = [
    {   question : "Om du går 65 Km/h, och du närmar dig ett bostadsområde måste du:",
        propositionA : "Du accelererar",
        propositionB : "Du behåller din hastighet, om du inte passerar andra fordon",
        propositionC : "Du saktar ner",
        propositionD : "Du behåller din hasighet",
        reponse : "C"},

    {   question : "Om du vrider höger vid ett trafikljus, men se en gångkorsning vad gör du:",
        propositionA : "Du passerar fotgängaren ",
        propositionB : "Du kontrollerar att det inte finns några andra fordon runt",
        propositionC : "Du väntar tills fotgängaren har korsat",
        propositionD : "Du skjuter fotgängaren och fortsätter att köra",
        reponse : "C"},

    {   question : "Utan någon tidigare indikation är hastigheten i ett bostadsområde: __ Km/h",
        propositionA : "30",
        propositionB : "35",
        propositionC : "40",
        propositionD : "45",
        reponse : "A"},

  {   question : "Innan varje körfältbyte måste du:",
        propositionA : "Kontrollera dina speglar",
        propositionB : "Kontrollera dina blinda fläckar",
        propositionC : "Signal your intentions",
        propositionD : "Alla ovanstående",
        reponse : "D"},

  {   question : "Vilken blodalkoholnivå klassificeras som körning medan den är berusad?",
        propositionA : "0.05%",
        propositionB : "0.20%",
        propositionC : "0.08%",
        propositionD : "0.06%",
        reponse : "C"},

  {   question : "När kan du fortsätta att köra vid ett trafikljus?",
        propositionA : "När den är grön",
        propositionB : "När det inte finns någon i korsningen",
        propositionC : "Du är i en skolson",
        propositionD : "När den är grön och / eller röd och du svänger höger",
        reponse : "D"},

  {   question : "En fotgängare har en krysssignal, vad gör du?",
        propositionA : "Du låter dem passera",
        propositionB : "Du observerar innan du fortsätter",
        propositionC : "Du vinkar för att berätta för dem att korsa",
        propositionD : "Du fortsätter eftersom ditt trafikljus är grönt",
        reponse : "D"},

  {   question : "Vad är tillåtet när du passerar ett annat fordon",
        propositionA : "Du följer det noggrant för att skicka det snabbare",
        propositionB : "Du skickar det utan att lämna vägen",
        propositionC : "Du kör på motsatt sida av vägen för att passera",
        propositionD : "Du överskrider hastighetsgränsen för att skicka dem",
        reponse : "C"},

  {   question : "Du kör på en motorväg som anger en maximal hastighet på 70 km / h. De flesta trafiken kör på 75 km / h, så du ska inte köra snabbare än:",
        propositionA : "50 Km/h",
        propositionB : "25 Km/h",
        propositionC : "30 Km/h",
        propositionD : "70 Km/h",
        reponse : "D"},

  {   question : "Om du blir påkörd utav ett annat fordon, så är det viktigt att:",
        propositionA : "Ta en promenad för att rensa tankarna.",
        propositionB : "Ta en selfie.",
        propositionC : "Attackera bilisten.",
        propositionD : "Åka in till sjukhuset.",
        reponse : "D"},
]
