var tableauQuestion = [
    {   question : "Om du åker i 80 Km/h, och du närmar dig ett bostadsområde måste du:",
        propositionA : "Du accelererar",
        propositionB : "Du behåller din hastighet, om du inte passerar andra fordon",
        propositionC : "Du saktar ner",
        propositionD : "Du behåller din hasighet",
        reponse : "C"},

    {   question : "Om du svänger höger vid ett trafikljus, men ser någon i en gångkorsning vad gör du:",
        propositionA : "Du passerar fotgängaren",
        propositionB : "Du kontrollerar att det inte finns några andra fordon runt",
        propositionC : "Du väntar tills fotgängaren har korsat",
        propositionD : "Du skjuter fotgängaren och fortsätter att köra",
        reponse : "C"},

    {   question : "Utan någon tidigare indikation är hastigheten i ett bostadsområde: __ Km/h",
        propositionA : "30",
        propositionB : "35",
        propositionC : "40",
        propositionD : "45",
        reponse : "A"},

  {   question : "Innan varje körfältbyte måste du:",
        propositionA : "Kontrollera dina speglar",
        propositionB : "Kontrollera dina blinda fläckar",
        propositionC : "Sätta på rätt blinkerljus",
        propositionD : "Alla ovanstående",
        reponse : "D"},

  {   question : "Vilken blodalkoholnivå klassificeras som körning medan den är berusad?",
        propositionA : "0.05%",
        propositionB : "0.20%",
        propositionC : "0.08%",
        propositionD : "0.06%",
        reponse : "C"},

  {   question : "När kan du fortsätta att köra vid ett trafikljus?",
        propositionA : "När det är grönt",
        propositionB : "När det inte finns någon i korsningen",
        propositionC : "När du är i en skol-zon",
        propositionD : "När den är grön och / eller röd och du svänger höger",
        reponse : "D"},

  {   question : "En fotgängare har en krysssignal, vad gör du?",
        propositionA : "Du låter dem passera",
        propositionB : "Du observerar innan du fortsätter",
        propositionC : "Du vinkar för att berätta för dem att korsa",
        propositionD : "Du fortsätter eftersom ditt trafikljus är grönt",
        reponse : "D"},

  {   question : "Vad är tillåtet när du passerar ett annat fordon",
        propositionA : "Du accelererar och kör fortare än befintlig hastighetsgräns",
        propositionB : "Du sätter på varningsblinker och passerar fordonet",
        propositionC : "Du kör på motsatt sida av vägen för att passera",
        propositionD : "Du sätter på helljus och passerar fordonet",
        reponse : "C"},

  {   question : "Du kör på en motorväg som anger en maximal hastighet på 70 km/h. De flesta trafiken kör 75 km/h, du ska inte köra snabbare än:",
        propositionA : "30 Km/h",
        propositionB : "50 Km/h",
        propositionC : "70 Km/h",
        propositionD : "75 Km/h",
        reponse : "C"},

  {   question : "Om du blir påkörd utav ett annat fordon, så är det viktigt att:",
        propositionA : "Ta en promenad för att rensa tankarna.",
        propositionB : "Ta en selfie.",
        propositionC : "Attackera bilisten.",
        propositionD : "Åka in till sjukhuset.",
        reponse : "D"},
]
